version: '3.8'
services:
  # Define the PostgreSQL service
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fplscraper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Define the Spring Boot service
  app:
    image: cseboo/fpl-scraper:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fplscraper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # Define the Flutter web application service
  client:
    image: cseboo/fpl-scraper-client:0.0.1
    ports:
      - "8081:8081"
    depends_on:
      - app
    environment:
      - FLUTTER_ENV=production

  # Define the Nginx reverse proxy service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/fplpicks.online/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/fplpicks.online/privkey.pem:/etc/ssl/certs/privkey.pem
    depends_on:
      - app
      - client

# Define named volumes for persistent storage
volumes:
  postgres-data:
