openapi: 3.0.3
info:
  title: Fantasy Premier League Scraper service API - OpenAPI 3.1.0
  description: FPL Scraper API Spec
  version: 1.0.0

paths:
  /player/data/update:
    get:
      tags:
        - player
      summary: Update players data by calling FPL server endpoint
      operationId: updatePlayers
      responses:
        201:
          description: 'Updated'
        400:
          description: 'invalid request'
        500:
          description: 'Server side error'

  /league/picks:
    post:
      tags:
        - league
      summary: Returns the players and participants, who selected them in the actual gameweek
      operationId: getPicks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PicksRequestBody'
      responses:
        200:
          description: 'Returns the picks of participants'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PicksResponseBody'
        400:
          description: 'invalid request'
        500:
          description: 'Server side error'
  /league/data/{leagueId}:
    get:
      tags:
        - league
      summary: Returns basic datas of the league
      operationId: getLeagueData
      parameters:
        - in: path
          description: 'League ID which league to query'
          name: leagueId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Returns basic data of the league'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeagueDataModel'

        400:
          description: 'invalid request'
        500:
          description: 'Server side error'

components:
  schemas:
    PicksRequestBody:
      type: object
      properties:
        playerIds:
          type: array
          items:
            type: integer
        gameweek:
          type: integer

    PicksResponseBody:
      description: Returns a list, which contains players and a list which contains which participant selected them.
      type: object
      properties:
        picks:
          type: array
          items:
            $ref: '#/components/schemas/PicksModel'

    PicksModel:
      description: Represents a list, which contains players and a list, which contains which participant selected them.
      type: object
      properties:
        playerId:
          description: 'ID of the football player'
          type: integer
        playerName:
          description: 'Name of the football player'
          type: string
        numberOfPicks:
          description: 'How many times the football player were picked'
          type: integer
        pickedBy:
          type: array
          items:
            $ref: '#/components/schemas/PlayerPickModel'

    PlayerPickModel:
      description: 'Represents a single pick of a football player by a participant.'
      type: object
      properties:
        id:
          description: 'ID of the participant'
          type: integer
        multiplier:
          description: 'Multiplier of the player'
          type: integer
      required:
        - id
        - name
        - multiplier

    LeagueDataModel:
      description: 'Contains basic data of the league'
      type: object
      properties:
        leagueName:
          description: 'Name of the league'
          type: string
        participants:
          additionalProperties:
            type: string